"""Driver protocol — interface for form-filling engines.

Both ExtensionBridge and PlaywrightDriver implement this protocol.
The ApplicationOrchestrator calls these methods without knowing which driver it uses.
"""
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class DriverProtocol(Protocol):
    """Structural interface for form-filling drivers."""

    async def navigate(self, url: str) -> dict: ...
    async def fill(self, selector: str, value: str) -> dict: ...
    async def click(self, selector: str) -> dict: ...
    async def select_option(self, selector: str, value: str) -> dict: ...
    async def check_box(self, selector: str, checked: bool) -> dict: ...
    async def fill_radio(self, selector: str, value: str) -> dict: ...
    async def fill_date(self, selector: str, value: str) -> dict: ...
    async def fill_autocomplete(self, selector: str, value: str) -> dict: ...
    async def fill_contenteditable(self, selector: str, value: str) -> dict: ...
    async def upload_file(self, selector: str, path: str) -> dict: ...
    async def screenshot(self) -> dict: ...
    async def get_snapshot(self, **kwargs) -> dict: ...
    async def scan_validation_errors(self) -> dict: ...
    async def close(self) -> None: ...
